name: Linux Packages
on:
  push:
    branches:
      - main
      - pbuilder
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  source-bundle:
    name: Source Bundle
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Install source dependencies
        shell: bash
        run: |
          sudo apt-get install qt5-default qttools5-dev-tools golang debhelper -y
          pip3 install "glean_parser==3.5"
          pip3 install pyhumps
          pip3 install pyyaml
      
      - name: Build source bundle
        shell: bash
        run: ./scripts/linux_script.sh --source
      
      - name: Uploading
        uses: actions/upload-artifact@v2
        with:
            name: Sources
            path: .tmp

  bionic-staging:
    name: Bionic Staging
    runs-on: ubuntu-18.04
    steps:
      - name: Install Linux packages
        run: |
          # Add external PPA, latest version of QT is 5.12.x for Ubuntu 18.04
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic -y
          sudo apt update
          sudo apt install git qt515tools qt515svg qt515networkauth-no-lgpl qt515charts-no-lgpl libgl-dev libpolkit-gobject-1-dev devscripts debhelper cdbs quilt qt515graphicaleffects qt515imageformats  qt515quickcontrols2   libxcb-image0-dev libxcb-shape0-dev libxcb-sync0-dev libxcb-render-util0-dev libxcb-xfixes0-dev libxcb-icccm4-dev libx11-xcb-dev libxcb-keysyms1-dev libasound2-dev libaudio-dev libcups2-dev libdbus-1-dev libglu1-mesa-dev  libmng-dev libtiff5-dev libxcursor-dev libxi-dev libxinerama-dev libxmu-dev libxrandr-dev libxv-dev libedit-dev libvulkan-dev qt515websockets python3-setuptools -y

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install glean depedencies
        shell: bash
        run: |
          pip3 install "glean_parser==3.5"
          pip3 install pyhumps
          pip3 install pyyaml

      - name: Create package structure
        shell: bash
        run: |
          export PATH=/opt/qt515/bin:$PATH
          ./scripts/linux_script.sh -s -r bionic
          mkdir packages
          cp .tmp/*.deb packages

      - name: Uploading
        uses: actions/upload-artifact@v1
        with:
            name: Staging Build (bionic)
            path: packages

  bionic-production:
    name: Bionic Production
    runs-on: ubuntu-18.04
    steps:
      - name: Install Linux packages
        run: |
          # Add external PPA, latest version of QT is 5.12.x for Ubuntu 18.04
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic -y
          sudo apt update
          sudo apt install git qt515tools qt515svg qt515networkauth-no-lgpl qt515charts-no-lgpl libgl-dev libpolkit-gobject-1-dev devscripts debhelper cdbs quilt qt515graphicaleffects qt515imageformats  qt515quickcontrols2   libxcb-image0-dev libxcb-shape0-dev libxcb-sync0-dev libxcb-render-util0-dev libxcb-xfixes0-dev libxcb-icccm4-dev libx11-xcb-dev libxcb-keysyms1-dev libasound2-dev libaudio-dev libcups2-dev libdbus-1-dev libglu1-mesa-dev  libmng-dev libtiff5-dev libxcursor-dev libxi-dev libxinerama-dev libxmu-dev libxrandr-dev libxv-dev libedit-dev libvulkan-dev qt515websockets python3-setuptools -y

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install glean depedencies
        shell: bash
        run: |
          pip3 install "glean_parser==3.5"
          pip3 install pyhumps
          pip3 install pyyaml

      - name: Create package structure
        shell: bash
        run: |
          export PATH=/opt/qt515/bin:$PATH
          ./scripts/linux_script.sh -r bionic
          mkdir packages
          cp .tmp/*.deb packages

      - name: Uploading
        uses: actions/upload-artifact@v1
        with:
            name: Production Build (bionic)
            path: packages

  ubuntu-packages:
    name: Ubuntu Packages
    needs: source-bundle
    strategy:
      matrix:
        config:
            - { name: "Focal", dist: focal, ppa: "ppa:beineri/opt-qt-5.15.2-focal" }
            - { name: "Hirsute", dist: hirsute, ppa: "" }

    runs-on: ubuntu-latest
    env:
      basetgz: "/var/cache/pbuilder/ubuntu-buildd-${{matrix.config.dist}}.tgz"
    steps:
      - name: Download Source Package
        uses: actions/download-artifact@v2
        with:
            name: Sources
      
      - name: Create base ${{matrix.config.dist}} image
        run: |
          # Create hooks for extra distributions
          mkdir hooks
          echo '#!/bin/sh' >> hooks/E01extradist
          for extra in ${{matrix.config.ppa}}; do
            if [[ $extra = ppa:* ]]; then
              PPA_USER=$(echo $extra | awk -F[:/] '{print $2}')
              PPA_NAME=$(echo $extra | awk -F[:/] '{print $3}')
              PPA_FINGERPRINT=$(wget -qO- "https://launchpad.net/api/1.0/~$PPA_USER/+archive/$PPA_NAME" | jq -r .signing_key_fingerprint)
              echo "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $PPA_FINGERPRINT" >> hooks/E01extradist
              DEB_MIRROR="deb http://ppa.launchpad.net/$PPA_USER/$PPA_NAME/ubuntu ${{matrix.config.dist}} main"
            fi
            echo "echo $DEB_MIRROR >> /etc/apt/sources.list" >> hooks/E01extradist
          done
          echo "apt-get update" >> hooks/E01extradist
          chmod +x hooks/E01extradist

          sudo apt-get install pbuilder debootstrap debhelper devscripts -y
          sudo pbuilder create --distribution ${{ matrix.config.dist }} --basetgz $basetgz --hookdir $(pwd)/hooks \
               --debootstrapopts --variant=buildd --extrapackages gnupg

      - name: Building package
        shell: bash
        run: |
          cd ${{matrix.config.dist}}-stage
          ln -s ../mozillavpn_*.orig.tar.gz
          sudo pbuilder build --basetgz $basetgz --hookdir $(pwd)/hooks --buildresult $(pwd) mozillavpn_*.dsc

      - name: Uploading
        uses: actions/upload-artifact@v1
        with:
            name: ${{matrix.config.name}} Build
            path: ${{matrix.config.dist}}-prod

  rpmbuild:
    name: RPM Packages
    needs: source-bundle
    runs-on: ubuntu-latest
    container:
      image: fedora:33

    steps:
      - name: Download Source Package
        uses: actions/download-artifact@v2
        with:
            name: Sources

      - name: Install Build Dependencies
        run: |
          yum -y install rpm-build rpmdevtools yum-utils
          yum-builddep -y mozillavpn.spec

      - name: Building package
        shell: bash 
        run: rpmbuild -D "_topdir $(pwd)" -D "_sourcedir $(pwd)" -ba mozillavpn.spec

      - name: Uploading
        uses: actions/upload-artifact@v2
        with:
            name: RPM Build
            path: |
              RPMS/
              SRPMS/

